name: Test and Lint

on:
  push:
    paths:
      - .github/workflows/test_lint.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up our JDK environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Update Play Public Key
        run: echo 'PLAY_PUBLIC_KEY=${{ secrets.PLAY_PUBLIC_KEY }}' > ./local.properties
      - name: Update Base Url
        run: echo 'BASE_URL=${{ secrets.BASE_URL }}' > ./local.properties
      - name: Update Firebase Base Url
        run: echo 'BASE_URL_FIREBASE_CLOUD=${{ secrets.BASE_URL_FIREBASE_CLOUD }}' > ./local.properties
      - name: Update Admob Full Screen AD Id
        run: echo 'FULL_SCREEN_AD_ID=${{ secrets.FULL_SCREEN_AD_ID }}' > ./local.properties
      - name: Update Admob AD Id
        run: echo 'AD_ID_PROJECT=${{ secrets.AD_ID_PROJECT }}' > ./local.properties
      - name: Update Add Weight Banner AD Id
        run: echo 'ADD_WEIGHT_AD_ID=${{ secrets.ADD_WEIGHT_AD_ID }}' > ./local.properties
      - name: Update Calendar Banner AD Id
        run: echo 'CALENDAR_AD_ID=${{ secrets.CALENDAR_AD_ID }}' > ./local.properties
      - name: Update Home Banner AD Id
        run: echo 'HOME_AD_ID=${{ secrets.HOME_AD_ID }}' > ./local.properties
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Unit tests results
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-results
          path: app/build/reports/tests/testDebugUnitTest/index.html

